name: Environment Testing
on:
  workflow_dispatch:

env:
  LUCKY_NUMBER: "8"

jobs:
  say_hello:
    runs-on: ubuntu-latest
    steps:
      - name: Install Dependencies
        if: env.LUCKY_NUMBER == '8'
        run: |
          echo "My lucky number: $LUCKY_NUMBER"
