name: "设置环境变量、调用环境变量            "
on:
  workflow_dispatch:

env:
  LUCKY_NUMBER: "8"

jobs:
  say_hello:
    runs-on: ubuntu-latest
    steps:
      - name: Testing
        if: env.LUCKY_NUMBER == '8'
        run: |
          echo "My lucky number: $LUCKY_NUMBER"
