name: "just curl"

on:
  workflow_dispatch:
    inputs:
      url:
        description: '请输入url：'
        required: true
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Run
        env:
          URL: ${{ github.event.inputs.url }}
        run: |
          curl "$URL"
